apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-saap-tls
  namespace: vault
spec:
  secretName: vault-saap-tls
  dnsNames:
    - vault.saap.dev
  issuerRef:
    name: my-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
