apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# To upgrade ArgoCD, increment the version here
# https://github.com/argoproj/argo-cd/tags
resources:
  - github.com:argoproj/argo-cd.git/manifests/cluster-install?ref=v2.10.1
  - argocd-namespace.yaml
  - argocd-ui-ingressroute.yaml
  - argocd-ui-ingress.yaml
  - argocd-clusterrolebinding.yaml

patchesStrategicMerge:
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml

generatorOptions:
  disableNameSuffixHash: true
