apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forecastle-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: git@github.com:stakater/saap-dev-gitops.git
    path: registry/saap/components/forecastle
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: forecastle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
