kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-runner-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: '0'
subjects:
  - kind: ServiceAccount
    name: github-runner
    namespace: github-runner
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io